use Mix.Config

config :whalewatch_app, base_url: "https://whalewatch.io"
config :whalewatch_app, :alerts, WhalewatchApp.Alerts
config :whalewatch_app, :notification_message, WhalewatchApp.Notifications.Message
config :whalewatch_app, :notificator, WhalewatchApp.Notifications.AlertFilter
config :whalewatch_app, :btc_ws_url, "wss://ws.blockchain.info/inv"
config :whalewatch_app, :enable_ws_watchers, System.get_env("ENABLE_WS_WATCHERS")
config :whalewatch_app, :enable_eth_watcher, System.get_env("ENABLE_ETH_WATCHER")
config :whalewatch_app, :enable_price_job, System.get_env("ENABLE_PRICE_JOB")
config :whalewatch_app, :infura_api_key, System.get_env("INFURA_API_KEY")

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# WhalewatchAppWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :whalewatch_app, WhalewatchAppWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "https://whalewatch.io", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

# Do not print debug messages in production
# config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :whalewatch_app, WhalewatchAppWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :whalewatch_app, WhalewatchAppWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :whalewatch_app, WhalewatchAppWeb.Endpoint, server: true
#

config :whalewatch_app, WhalewatchApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true

config :whalewatch_app, WhalewatchApp.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "",
  hostname: "",
  port: 587,
  username: {:system, "SMTP_USERNAME"},
  password: {:system, "SMTP_PASSWORD"},
  tls: :always,
  allowed_tls_versions: [:"tlsv1", :"tlsv1.1", :"tlsv1.2"],
  ssl: false,
  retries: 1,
  no_mx_lookups: false,
  auth: :always
